[workspace]
resolver = "2"

members = [
    "async1", "async2",
    "byte",
    "command",
    "filter",
    "lc",
    "lifesim",
    "multitype",
    "ownership",
    "simplematch",
    "split", "stringmanip",
    "wc-rs",
]
