[package]
name = "async1"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
async-lock = "3.4.0"
async-std = { version = "1.13.1", features = ["attributes"] }
clap = { version = "4.5.38", features = ["derive"] }
git2 = "0.20.2"
